version: "3.3"
services:
  order_service:
    image: ngudkov/order_service:1.3
    ports:
      - 8081:8081
    environment:
      - ACTIVEMQ_HOST=activemq
      - MYSQL_HOST=mysql
      - CLIENT_ID=
      - CLIENT_SECRET=
      - AZURE_AD_TENANT_ID=
    links:
      - activemq
      - mysql
  log_service:
    image: ngudkov/log_service:1.3
    ports:
      - 8080:8080
    environment:
      - ACTIVEMQ_HOST=activemq
    links:
      - activemq
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
  mysql:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_ROOT_PASSWORD=root
