apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o settings.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: activemq
      name: activemq
    spec:
      ports:
        - name: "61616"
          port: 61616
          targetPort: 61616
        - name: "8161"
          port: 8161
          targetPort: 8161
      selector:
        io.kompose.service: activemq
    status:
      loadBalancer: { }
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o settings.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
      name: web
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: web
    status:
      loadBalancer: { }
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o settings.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: activemq
      name: activemq
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: activemq
      strategy: { }
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
              convert -o settings.yml
            kompose.version: 1.21.0 (992df58d8)
          creationTimestamp: null
          labels:
            io.kompose.service: activemq
        spec:
          containers:
            - image: rmohr/activemq:5.15.9
              imagePullPolicy: ""
              name: activemq
              ports:
                - containerPort: 61616
                - containerPort: 8161
              resources: { }
          restartPolicy: Always
          serviceAccountName: ""
          volumes: null
    status: { }
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -o settings.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
      name: web
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: web
      strategy: { }
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
              convert -o settings.yml
            kompose.version: 1.21.0 (992df58d8)
          creationTimestamp: null
          labels:
            io.kompose.service: web
        spec:
          containers:
            - env:
                - name: spring.activemq.broker-url
                  value: tcp://activemq:61616
              image: ngudkov/kubernetes-demo:1.6
              imagePullPolicy: ""
              name: web
              ports:
                - containerPort: 8080
              resources: { }
          restartPolicy: Always
          serviceAccountName: ""
          volumes: null
    status: { }
kind: List
metadata: { }

